"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type Props = {
  schoolName: string;
  schoolAddress?: string;
schoolLogo?: string;
  reportTitle?: string;

  summary: {
    expectedFees: number;
    collected: number;
    outstanding: number;
    income: number;
    expenses: number;
    netIncome: number;
  };

  rows: any[];
};

const ExportPDF = ({
  schoolName,
  schoolAddress,
  schoolLogo,
  reportTitle = "Financial Report",
  summary,
  rows,
}: Props) => {
  const loadImage = (url: string) =>
  new Promise<string>((resolve, reject) => {
    const image = new Image();

    image.crossOrigin = "Anonymous";

    image.onload = () => {
      const canvas =
        document.createElement("canvas");

      canvas.width = image.width;

      canvas.height = image.height;

      const ctx = canvas.getContext("2d");

      if (!ctx) {
  reject(new Error("Canvas context unavailable"));
  return;
}

      ctx.drawImage(image, 0, 0);

      resolve(canvas.toDataURL("image/png"));
    };

    image.onerror = reject;

    image.src = url;
  });
  

  const exportPDF = async () => {
    let logo: string | null = null;

  if (schoolLogo) {
    try {
      logo = await loadImage(schoolLogo);
    } catch {
      logo = null;
    }
  }
 
    const doc = new jsPDF();

    if (logo) {
  doc.addImage(
    logo,
    "PNG",
    14,
    10,
    20,
    20
  );
}



    doc.setFontSize(22);

doc.text(
  schoolName,
  logo ? 40 : 14,
  18
);

doc.setFontSize(11);

doc.setFont("helvetica", "normal");

if (schoolAddress) {
  doc.text(
  schoolAddress,
  logo ? 40 : 14,
  25
);
}

doc.setFontSize(17);

doc.setFont("helvetica", "bold");

doc.text(
  reportTitle,
  14,
  38
);

doc.setFontSize(10);

doc.setFont("helvetica", "normal");

doc.text(
  `Generated: ${new Date().toLocaleString()}`,
  14,
  45
);


doc.setDrawColor(220);

doc.line(
  14,
  50,
  195,
  50
);

doc.setFontSize(11);

doc.setFont("helvetica", "bold");

doc.text(
  "Financial Summary",
  14,
  60
);

doc.setFont("helvetica", "normal");

doc.text(
  `Expected Fees: ₦${summary.expectedFees.toLocaleString()}`,
  14,
  68
);

doc.text(
  `Collected: ₦${summary.collected.toLocaleString()}`,
  14,
  76
);

doc.text(
  `Outstanding: ₦${summary.outstanding.toLocaleString()}`,
  14,
  84
);

doc.text(
  `Other Income: ₦${summary.income.toLocaleString()}`,
  100,
  68
);

doc.text(
  `Expenses: ₦${summary.expenses.toLocaleString()}`,
  100,
  76
);

doc.text(
  `Net Income: ₦${summary.netIncome.toLocaleString()}`,
  100,
  84
);

        autoTable(doc, {
      startY: 95,

      head: [[
        "Type",
        "Title",
        "Description",
        "Amount",
        "Date",
      ]],

      body: rows.map((row) => [
        row.type,
        row.title,
        row.subtitle,
        `₦${Number(row.amount).toLocaleString()}`,
        new Date(row.date).toLocaleDateString(),
      ]),

      styles: {
        fontSize: 9,
        cellPadding: 3,
      },

      headStyles: {
        fillColor: [75, 85, 99],
        textColor: 255,
      },

      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
    });

    const pageHeight =
      doc.internal.pageSize.height;

    doc.setFontSize(10);

    doc.setDrawColor(220);

doc.line(
  14,
  pageHeight - 30,
  195,
  pageHeight - 30
);

doc.setFontSize(10);

doc.text(
  "Prepared By",
  18,
  pageHeight - 18
);

doc.text(
  "__________________",
  14,
  pageHeight - 10
);

doc.text(
  "Approved By",
  120,
  pageHeight - 18
);

doc.text(
  "__________________",
  115,
  pageHeight - 10
);

doc.setFontSize(8);

doc.text(
  "Generated by Rubix School ERP",
  70,
  pageHeight - 2
);

    doc.save("Financial_Report.pdf");
  };

    return (
    <button
      onClick={exportPDF}
      className="
        rounded-xl
        bg-red-600
        px-4
        py-2
        text-white
        font-semibold
        hover:bg-red-700
        transition
      "
    >
      📄 Export PDF
    </button>
  );
};

export default ExportPDF;